### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by VladislavAnkudinov** [technicalmachine/start.tessel.io#90]
on macOS Sierra, downgraded node version to 0.12.7, then installed tessel, running `tessel update` and get this error `TESSEL? ERR! No devices found.`. Of course device plugged to USB but I can see red LED lights

**Comment by rwaldron** [comment]
> downgraded node version to 0.12.7

This version of Node.js is not supported, please use only Node.js LTS releases: 4.x or 6.x. Issues with the CLI should be filed in the [t2-cli](https://github.com/tessel/t2-cli) repo. 

Thanks!

**Comment by johnnyman727** [comment]
It looks like this is a Tessel 1 use based on the version of the CLI.

**Comment by rwaldron** [comment]
Oh, I see... because `tessel update`, instead of `t2 update`

**Comment by VladislavAnkudinov** [comment]
yes, I am using tessel 1, also i cant see it in USB list on Linux nor on macOS, probably its dead(
